# This file contains fake pay data for development purposes and the data may differ from the actual pay data. The pay data below is based off
# previous awards and is subject to change following the 2026 pay award. The pay data is used to calculate the pay increase for each pay band and
# spine point based on the current pay and the future pay.

development: &default
  paybands_and_spine_points:
    unqualified:
      unq1: Unqualified Pay Range 1 (UnQ1)
      unq2: Unqualified Pay Range 2 (UnQ2)
      unq3: Unqualified Pay Range 3 (UnQ3)
      unq4: Unqualified Pay Range 4 (UnQ4)
      unq5: Unqualified Pay Range 5 (UnQ5)
      unq6: Unqualified Pay Range 6 (UnQ6)
    main:
      m1: Main Pay Range 1 (M1)
      m2: Main Pay Range 2 (M2)
      m3: Main Pay Range 3 (M3)
      m4: Main Pay Range 4 (M4)
      m5: Main Pay Range 5 (M5)
      m6: Main Pay Range 6 (M6)
    upper:
      u1: Upper Pay Range (U1)
      u2: Upper Pay Range (U2)
      u3: Upper Pay Range (U3)
    other:
      leading_practitioner: Leading Practitioner
      leadership: Leadership

  areas:
    inner_london: Inner London
    outer_london: Outer London
    london_fringe: Fringe of London
    rest_of_england: Rest of England

  pay_ranges:
    unq1:
      rest_of_england:
        current: [22601]
        first_year_future: [23732]
        second_year_future: [24444]
      london_fringe:
        current: [24066]
        first_year_future: [24909]
        second_year_future: [25657]
      outer_london:
        current: [26789]
        first_year_future: [27727]
        second_year_future: [28559]
      inner_london:
        current: [28343]
        first_year_future: [29336]
        second_year_future: [30217]
    unq2:
      rest_of_england:
        current: [25193]
        first_year_future: [26075]
        second_year_future: [26858]
      london_fringe:
        current: [26656]
        first_year_future: [27589]
        second_year_future: [28417]
      outer_london:
        current: [29383]
        first_year_future: [30412]
        second_year_future: [31325]
      inner_london:
        current: [30935]
        first_year_future: [32018]
        second_year_future: [32979]
    unq3:
      rest_of_england:
        current: [27785]
        first_year_future: [28758]
        second_year_future: [29621]
      london_fringe:
        current: [29248]
        first_year_future: [30272]
        second_year_future: [31181]
      outer_london:
        current: [31974]
        first_year_future: [33094]
        second_year_future: [34087]
      inner_london:
        current: [33528]
        first_year_future: [34702]
        second_year_future: [35744]
    unq4:
      rest_of_england:
        current: [30071]
        first_year_future: [31124]
        second_year_future: [32058]
      london_fringe:
        current: [31532]
        first_year_future: [32636]
        second_year_future: [33616]
      outer_london:
        current: [34265]
        first_year_future: [35465]
        second_year_future: [36529]
      inner_london:
        current: [35814]
        first_year_future: [37068]
        second_year_future: [38181]
    unq5:
      rest_of_england:
        current: [32667]
        first_year_future: [33811]
        second_year_future: [34826]
      london_fringe:
        current: [34126]
        first_year_future: [35321]
        second_year_future: [36381]
      outer_london:
        current: [36856]
        first_year_future: [38146]
        second_year_future: [39291]
      inner_london:
        current: [38402]
        first_year_future: [39747]
        second_year_future: [40940]
    unq6:
      rest_of_england:
        current: [35259]
        first_year_future: [36494]
        second_year_future: [37589]
      london_fringe:
        current: [36718]
        first_year_future: [38004]
        second_year_future: [39145]
      outer_london:
        current: [39450]
        first_year_future: [40831]
        second_year_future: [42056]
      inner_london:
        current: [40994]
        first_year_future: [42429]
        second_year_future: [43702]
    m1:
      rest_of_england:
        current: [32916]
        first_year_future: [34069]
        second_year_future: [35092]
      london_fringe:
        current: [34398]
        first_year_future: [35602]
        second_year_future: [36671]
      outer_london:
        current: [37870]
        first_year_future: [39196]
        second_year_future: [40372]
      inner_london:
        current: [40317]
        first_year_future: [41729]
        second_year_future: [42981]
    m2:
      rest_of_england:
        current: [34823]
        first_year_future: [36042]
        second_year_future: [37124]
      london_fringe:
        current: [36373]
        first_year_future: [37647]
        second_year_future: [38777]
      outer_london:
        current: [39851]
        first_year_future: [41246]
        second_year_future: [42484]
      inner_london:
        current: [42234]
        first_year_future: [43713]
        second_year_future: [45025]
    m3:
      rest_of_england:
        current: [37101]
        first_year_future: [38400]
        second_year_future: [39552]
      london_fringe:
        current: [38627]
        first_year_future: [39979]
        second_year_future: [41179]
      outer_london:
        current: [41935]
        first_year_future: [43403]
        second_year_future: [44706]
      inner_london:
        current: [44238]
        first_year_future: [45787]
        second_year_future: [47161]
    m4:
      rest_of_england:
        current: [39556]
        first_year_future: [40941]
        second_year_future: [42170]
      london_fringe:
        current: [41075]
        first_year_future: [42513]
        second_year_future: [43789]
      outer_london:
        current: [44128]
        first_year_future: [45673]
        second_year_future: [47044]
      inner_london:
        current: [46339]
        first_year_future: [47961]
        second_year_future: [49400]
    m5:
      rest_of_england:
        current: [42057]
        first_year_future: [43529]
        second_year_future: [44835]
      london_fringe:
        current: [43545]
        first_year_future: [45070]
        second_year_future: [46423]
      outer_london:
        current: [46800]
        first_year_future: [48438]
        second_year_future: [49892]
      inner_london:
        current: [48952]
        first_year_future: [50666]
        second_year_future: [52186]
    m6:
      rest_of_england:
        current: [45352]
        first_year_future: [46940]
        second_year_future: [48349]
      london_fringe:
        current: [46839]
        first_year_future: [48479]
        second_year_future: [49934]
      outer_london:
        current: [50474]
        first_year_future: [52241]
        second_year_future: [53809]
      inner_london:
        current: [52300]
        first_year_future: [54131]
        second_year_future: [55755]
    u1:
      rest_of_england:
        current: [47472]
        first_year_future: [49134]
        second_year_future: [50609]
      london_fringe:
        current: [48913]
        first_year_future: [50625]
        second_year_future: [52144]
      outer_london:
        current: [52219]
        first_year_future: [54047]
        second_year_future: [55669]
      inner_london:
        current: [57632]
        first_year_future: [59650]
        second_year_future: [61440]
    u2:
      rest_of_england:
        current: [49232]
        first_year_future: [50956]
        second_year_future: [52485]
      london_fringe:
        current: [50668]
        first_year_future: [52442]
        second_year_future: [54016]
      outer_london:
        current: [54151]
        first_year_future: [56047]
        second_year_future: [57729]
      inner_london:
        current: [60464]
        first_year_future: [62581]
        second_year_future: [64459]
    u3:
      rest_of_england:
        current: [51048]
        first_year_future: [52835]
        second_year_future: [54421]
      london_fringe:
        current: [52490]
        first_year_future: [54328]
        second_year_future: [55958]
      outer_london:
        current: [56154]
        first_year_future: [58120]
        second_year_future: [59864]
      inner_london:
        current: [62496]
        first_year_future: [64684]
        second_year_future: [66625]

    leading_practitioner:
      rest_of_england:
        current: [52026, 79092]
        first_year_future: [53847, 81861]
        second_year_future: [55463, 83417]
      london_fringe:
        current: [53460, 80528]
        first_year_future: [55332, 83347]
        second_year_future: [56992, 85848]
      outer_london:
        current: [56154, 83223]
        first_year_future: [58120, 86136]
        second_year_future: [59864, 88721]
      inner_london:
        current: [61858, 88930]
        first_year_future: [64024, 92043]
        second_year_future: [65945, 94805]
    leadership:
      rest_of_england:
        current: [51773, 143796]
        first_year_future: [53586, 148829]
        second_year_future: [55194, 153294]
      london_fringe:
        current: [53198, 145218]
        first_year_future: [55060, 150301]
        second_year_future: [56712, 154811]
      outer_london:
        current: [55881, 147866]
        first_year_future: [57837, 153042]
        second_year_future: [59573, 157634]
      inner_london:
        current: [61554, 153490]
        first_year_future: [63709, 158863]
        second_year_future: [65621, 163629]

test:
  paybands_and_spine_points: {}
  areas: {}
  pay_ranges: {}

production:
  <<: *default
