development: &default
  paybands_and_spine_points:
    unqualified:
      unq1: Unqualified Pay Range 1 (UnQ1)
      unq2: Unqualified Pay Range 2 (UnQ2)
      unq3: Unqualified Pay Range 3 (UnQ3)
      unq4: Unqualified Pay Range 4 (UnQ4)
      unq5: Unqualified Pay Range 5 (UnQ5)
      unq6: Unqualified Pay Range 6 (UnQ6)
    main:
      m1: Main Pay Range 1 (M1)
      m2: Main Pay Range 2 (M2)
      m3: Main Pay Range 3 (M3)
      m4: Main Pay Range 4 (M4)
      m5: Main Pay Range 5 (M5)
      m6: Main Pay Range 6 (M6)
    upper:
      u1: Upper Pay Range (U1)
      u2: Upper Pay Range (U2)
      u3: Upper Pay Range (U3)
    other:
      leading_practitioner: Leading Practitioner
      leadership: Leadership

  areas:
    inner_london: Inner London
    outer_london: Outer London
    london_fringe: Fringe of London
    rest_of_england: Rest of England

  pay_ranges:
    unq1:
      rest_of_england:
        current: [21731]
        future: [22601]
      london_fringe:
        current: [23140]
        future: [24066]
      outer_london:
        current: [25758]
        future: [26789]
      inner_london:
        current: [27252]
        future: [28343]
    unq2:
      rest_of_england:
        current: [24224]
        future: [25193]
      london_fringe:
        current: [25630]
        future: [26656]
      outer_london:
        current: [28252]
        future: [29383]
      inner_london:
        current: [29745]
        future: [30935]
    unq3:
      rest_of_england:
        current: [26716]
        future: [27785]
      london_fringe:
        current: [28123]
        future: [29248]
      outer_london:
        current: [30744]
        future: [31974]
      inner_london:
        current: [32238]
        future: [33528]
    unq4:
      rest_of_england:
        current: [28914]
        future: [30071]
      london_fringe:
        current: [30319]
        future: [31532]
      outer_london:
        current: [32947]
        future: [34265]
      inner_london:
        current: [34436]
        future: [35814]
    unq5:
      rest_of_england:
        current: [31410]
        future: [32667]
      london_fringe:
        current: [32813]
        future: [34126]
      outer_london:
        current: [35438]
        future: [36856]
      inner_london:
        current: [36925]
        future: [38402]
    unq6:
      rest_of_england:
        current: [33902]
        future: [35259]
      london_fringe:
        current: [35305]
        future: [36718]
      outer_london:
        current: [37932]
        future: [39450]
      inner_london:
        current: [39417]
        future: [40994]
    m1:
      rest_of_england:
        current: [31650]
        future: [32916]
      london_fringe:
        current: [33075]
        future: [34398]
      outer_london:
        current: [36413]
        future: [37870]
      inner_london:
        current: [38766]
        future: [40317]
    m2:
      rest_of_england:
        current: [33483]
        future: [34823]
      london_fringe:
        current: [34974]
        future: [36373]
      outer_london:
        current: [38318]
        future: [39851]
      inner_london:
        current: [40609]
        future: [42234]
    m3:
      rest_of_england:
        current: [35674]
        future: [37101]
      london_fringe:
        current: [37141]
        future: [38627]
      outer_london:
        current: [40322]
        future: [41935]
      inner_london:
        current: [42536]
        future: [44238]
    m4:
      rest_of_england:
        current: [38034]
        future: [39556]
      london_fringe:
        current: [39495]
        future: [41075]
      outer_london:
        current: [42430]
        future: [44128]
      inner_london:
        current: [44556]
        future: [46339]
    m5:
      rest_of_england:
        current: [40439]
        future: [42057]
      london_fringe:
        current: [41870]
        future: [43545]
      outer_london:
        current: [45000]
        future: [46800]
      inner_london:
        current: [47069]
        future: [48952]
    m6:
      rest_of_england:
        current: [43607]
        future: [45352]
      london_fringe:
        current: [45037]
        future: [46839]
      outer_london:
        current: [48532]
        future: [50474]
      inner_london:
        current: [50288]
        future: [52300]
    u1:
      rest_of_england:
        current: [45646]
        future: [47472]
      london_fringe:
        current: [47031]
        future: [48913]
      outer_london:
        current: [50210]
        future: [52219]
      inner_london:
        current: [55415]
        future: [57632]
    u2:
      rest_of_england:
        current: [47338]
        future: [49232]
      london_fringe:
        current: [48719]
        future: [50668]
      outer_london:
        current: [52068]
        future: [54151]
      inner_london:
        current: [58138]
        future: [60464]
    u3:
      rest_of_england:
        current: [49084]
        future: [51048]
      london_fringe:
        current: [50471]
        future: [52490]
      outer_london:
        current: [53994]
        future: [56154]
      inner_london:
        current: [60092]
        future: [62496]

    leading_practitioner:
      rest_of_england:
        current: [50025, 76050]
        future: [52026, 79092]
      london_fringe:
        current: [51403, 77430]
        future: [53460, 80528]
      outer_london:
        current: [53994, 80022]
        future: [56154, 83223]
      inner_london:
        current: [59478, 85509]
        future: [61858, 88930]
    leadership:
      rest_of_england:
        current: [49781, 138265]
        future: [51773, 143796]
      london_fringe:
        current: [51151, 139632]
        future: [53198, 145218]
      outer_london:
        current: [53731, 142178]
        future: [55881, 147866]
      inner_london:
        current: [59186, 147586]
        future: [61554, 153490]

test:
  paybands_and_spine_points: {}
  areas: {}
  pay_ranges: {}

production:
  <<: *default
