development: &default
  paybands_and_spine_points:
    unqualified:
      unq1: Unqualified Pay Range 1 (UnQ1)
      unq2: Unqualified Pay Range 2 (UnQ2)
      unq3: Unqualified Pay Range 3 (UnQ3)
      unq4: Unqualified Pay Range 4 (UnQ4)
      unq5: Unqualified Pay Range 5 (UnQ5)
      unq6: Unqualified Pay Range 6 (UnQ6)
    main:
      m1: Main Pay Range 1 (M1)
      m2: Main Pay Range 2 (M2)
      m3: Main Pay Range 3 (M3)
      m4: Main Pay Range 4 (M4)
      m5: Main Pay Range 5 (M5)
      m6: Main Pay Range 6 (M6)
    upper:
      u1: Upper Pay Range (U1)
      u2: Upper Pay Range (U2)
      u3: Upper Pay Range (U3)
    other:
      leading_practitioner: Leading Practitioner
      leadership: Leadership

  areas:
    inner_london: Inner London
    outer_london: Outer London
    london_fringe: Fringe of London
    rest_of_england: Rest of England

  pay_ranges:
    unq1:
      rest_of_england:
        current: [19340]
        future: [20598]
      london_fringe:
        current: [20594]
        future: [21933]
      outer_london:
        current: [22924]
        future: [24415]
      inner_london:
        current: [24254]
        future: [25831]
    unq2:
      rest_of_england:
        current: [21559]
        future: [22961]
      london_fringe:
        current: [22810]
        future: [24293]
      outer_london:
        current: [25144]
        future: [26779]
      inner_london:
        current: [26473]
        future: [28194]
    unq3:
      rest_of_england:
        current: [23777]
        future: [25323]
      london_fringe:
        current: [25029]
        future: [26656]
      outer_london:
        current: [27362]
        future: [29141]
      inner_london:
        current: [28692]
        future: [30557]
    unq4:
      rest_of_england:
        current: [25733]
        future: [27406]
      london_fringe:
        current: [26984]
        future: [28738]
      outer_london:
        current: [29323]
        future: [31229]
      inner_london:
        current: [30647]
        future: [32640]
    unq5:
      rest_of_england:
        current: [27954]
        future: [29772]
      london_fringe:
        current: [29203]
        future: [31102]
      outer_london:
        current: [31539]
        future: [33590]
      inner_london:
        current: [32863]
        future: [35000]
    unq6:
      rest_of_england:
        current: [30172]
        future: [32134]
      london_fringe:
        current: [31421]
        future: [33464]
      outer_london:
        current: [33759]
        future: [35954]
      inner_london:
        current: [35081]
        future: [37362]
    m1:
      rest_of_england:
        current: [28000]
        future: [30000]
      london_fringe:
        current: [29344]
        future: [31350]
      outer_london:
        current: [32407]
        future: [34514]
      inner_london:
        current: [34502]
        future: [36745]
    m2:
      rest_of_england:
        current: [29800]
        future: [31737]
      london_fringe:
        current: [31126]
        future: [33150]
      outer_london:
        current: [34103]
        future: [36320]
      inner_london:
        current: [36141]
        future: [38491]
    m3:
      rest_of_england:
        current: [31750]
        future: [33814]
      london_fringe:
        current: [33055]
        future: [35204]
      outer_london:
        current: [35886]
        future: [38219]
      inner_london:
        current: [37857]
        future: [40318]
    m4:
      rest_of_england:
        current: [33850]
        future: [36051]
      london_fringe:
        current: [35151]
        future: [37436]
      outer_london:
        current: [37763]
        future: [40218]
      inner_london:
        current: [39655]
        future: [42233]
    m5:
      rest_of_england:
        current: [35990]
        future: [38330]
      london_fringe:
        current: [37264]
        future: [39687]
      outer_london:
        current: [40050]
        future: [42654]
      inner_london:
        current: [41892]
        future: [44615]
    m6:
      rest_of_england:
        current: [38810]
        future: [41333]
      london_fringe:
        current: [40083]
        future: [42689]
      outer_london:
        current: [43193]
        future: [46001]
      inner_london:
        current: [44756]
        future: [47666]
    u1:
      rest_of_england:
        current: [40625]
        future: [43266]
      london_fringe:
        current: [41858]
        future: [44579]
      outer_london:
        current: [44687]
        future: [47592]
      inner_london:
        current: [49320]
        future: [52526]
    u2:
      rest_of_england:
        current: [42131]
        future: [44870]
      london_fringe:
        current: [43360]
        future: [46179]
      outer_london:
        current: [46340]
        future: [49353]
      inner_london:
        current: [51743]
        future: [55107]
    u3:
      rest_of_england:
        current: [43685]
        future: [46525]
      london_fringe:
        current: [44919]
        future: [47839]
      outer_london:
        current: [48055]
        future: [51179]
      inner_london:
        current: [53482]
        future: [56959]

    leading_practitioner:
      rest_of_england:
        current: [44523, 67685]
        future: [47417, 72085]
      london_fringe:
        current: [45749, 68913]
        future: [48723, 73393]
      outer_london:
        current: [48055, 71220]
        future: [51179, 75850]
      inner_london:
        current: [52936, 76104]
        future: [56377, 81051]
    leadership:
      rest_of_england:
        current: [44305, 123057]
        future: [47185, 131056]
      london_fringe:
        current: [45524, 124274]
        future: [48484, 132352]
      outer_london:
        current: [47820, 126539]
        future: [50929, 134765]
      inner_london:
        current: [52676, 131353]
        future: [56100, 139891]

test:
  paybands_and_spine_points: {}
  areas: {}
  pay_ranges: {}

production:
  <<: *default
