# This file contains fake pay data for development purposes and the data may differ from the actual pay data. The pay data below is based off
# previous awards and is subject to change following the 2026 pay award. The pay data is used to calculate the pay increase for each pay band and
# spine point based on the current pay and the future pay.

development: &default
  paybands_and_spine_points:
    unqualified:
      unq1: Unqualified Pay Range 1 (UnQ1)
      unq2: Unqualified Pay Range 2 (UnQ2)
      unq3: Unqualified Pay Range 3 (UnQ3)
      unq4: Unqualified Pay Range 4 (UnQ4)
      unq5: Unqualified Pay Range 5 (UnQ5)
      unq6: Unqualified Pay Range 6 (UnQ6)
    main:
      m1: Main Pay Range 1 (M1)
      m2: Main Pay Range 2 (M2)
      m3: Main Pay Range 3 (M3)
      m4: Main Pay Range 4 (M4)
      m5: Main Pay Range 5 (M5)
      m6: Main Pay Range 6 (M6)
    upper:
      u1: Upper Pay Range (U1)
      u2: Upper Pay Range (U2)
      u3: Upper Pay Range (U3)
    other:
      leading_practitioner: Leading Practitioner
      leadership: Leadership

  areas:
    inner_london: Inner London
    outer_london: Outer London
    london_fringe: Fringe of London
    rest_of_england: Rest of England

  pay_ranges:
    unq1:
      rest_of_england:
        current: [21731]
        first_year_future: [22601]
        second_year_future: [23731]
      london_fringe:
        current: [23140]
        first_year_future: [24066]
        second_year_future: [25269]
      outer_london:
        current: [25758]
        first_year_future: [26789]
        second_year_future: [28128]
      inner_london:
        current: [27252]
        first_year_future: [28343]
        second_year_future: [29760]
    unq2:
      rest_of_england:
        current: [24224]
        first_year_future: [25193]
        second_year_future: [26452]
      london_fringe:
        current: [25630]
        first_year_future: [26656]
        second_year_future: [27988]
      outer_london:
        current: [28252]
        first_year_future: [29383]
        second_year_future: [30852]
      inner_london:
        current: [29745]
        first_year_future: [30935]
        second_year_future: [32481]
    unq3:
      rest_of_england:
        current: [26716]
        first_year_future: [27785]
        second_year_future: [29174]
      london_fringe:
        current: [28123]
        first_year_future: [29248]
        second_year_future: [30710]
      outer_london:
        current: [30744]
        first_year_future: [31974]
        second_year_future: [33572]
      inner_london:
        current: [32238]
        first_year_future: [33528]
        second_year_future: [35204]
    unq4:
      rest_of_england:
        current: [28914]
        first_year_future: [30071]
        second_year_future: [31574]
      london_fringe:
        current: [30319]
        first_year_future: [31532]
        second_year_future: [33108]
      outer_london:
        current: [32947]
        first_year_future: [34265]
        second_year_future: [35978]
      inner_london:
        current: [34436]
        first_year_future: [35814]
        second_year_future: [37604]
    unq5:
      rest_of_england:
        current: [31410]
        first_year_future: [32667]
        second_year_future: [34300]
      london_fringe:
        current: [32813]
        first_year_future: [34126]
        second_year_future: [35832]
      outer_london:
        current: [35438]
        first_year_future: [36856]
        second_year_future: [38698]
      inner_london:
        current: [36925]
        first_year_future: [38402]
        second_year_future: [40322]
    unq6:
      rest_of_england:
        current: [33902]
        first_year_future: [35259]
        second_year_future: [37021]
      london_fringe:
        current: [35305]
        first_year_future: [36718]
        second_year_future: [38553]
      outer_london:
        current: [37932]
        first_year_future: [39450]
        second_year_future: [41422]
      inner_london:
        current: [39417]
        first_year_future: [40994]
        second_year_future: [43043]
    m1:
      rest_of_england:
        current: [31650]
        first_year_future: [32916]
        second_year_future: [34561]
      london_fringe:
        current: [33075]
        first_year_future: [34398]
        second_year_future: [36117]
      outer_london:
        current: [36413]
        first_year_future: [37870]
        second_year_future: [39763]
      inner_london:
        current: [38766]
        first_year_future: [40317]
        second_year_future: [42332]
    m2:
      rest_of_england:
        current: [33483]
        first_year_future: [34823]
        second_year_future: [36564]
      london_fringe:
        current: [34974]
        first_year_future: [36373]
        second_year_future: [38191]
      outer_london:
        current: [38318]
        first_year_future: [39851]
        second_year_future: [41843]
      inner_london:
        current: [40609]
        first_year_future: [42234]
        second_year_future: [44345]
    m3:
      rest_of_england:
        current: [35674]
        first_year_future: [37101]
        second_year_future: [38956]
      london_fringe:
        current: [37141]
        first_year_future: [38627]
        second_year_future: [40558]
      outer_london:
        current: [40322]
        first_year_future: [41935]
        second_year_future: [44031]
      inner_london:
        current: [42536]
        first_year_future: [44238]
        second_year_future: [46449]
    m4:
      rest_of_england:
        current: [38034]
        first_year_future: [39556]
        second_year_future: [41533]
      london_fringe:
        current: [39495]
        first_year_future: [41075]
        second_year_future: [43128]
      outer_london:
        current: [42430]
        first_year_future: [44128]
        second_year_future: [46334]
      inner_london:
        current: [44556]
        first_year_future: [46339]
        second_year_future: [48655]
    m5:
      rest_of_england:
        current: [40439]
        first_year_future: [42057]
        second_year_future: [44159]
      london_fringe:
        current: [41870]
        first_year_future: [43545]
        second_year_future: [45722]
      outer_london:
        current: [45000]
        first_year_future: [46800]
        second_year_future: [49140]
      inner_london:
        current: [47069]
        first_year_future: [48952]
        second_year_future: [51399]
    m6:
      rest_of_england:
        current: [43607]
        first_year_future: [45352]
        second_year_future: [47619]
      london_fringe:
        current: [45037]
        first_year_future: [46839]
        second_year_future: [49180]
      outer_london:
        current: [48532]
        first_year_future: [50474]
        second_year_future: [52997]
      inner_london:
        current: [50288]
        first_year_future: [52300]
        second_year_future: [54915]
    u1:
      rest_of_england:
        current: [45646]
        first_year_future: [47472]
        second_year_future: [49845]
      london_fringe:
        current: [47031]
        first_year_future: [48913]
        second_year_future: [51358]
      outer_london:
        current: [50210]
        first_year_future: [52219]
        second_year_future: [54829]
      inner_london:
        current: [55415]
        first_year_future: [57632]
        second_year_future: [60513]
    u2:
      rest_of_england:
        current: [47338]
        first_year_future: [49232]
        second_year_future: [51693]
      london_fringe:
        current: [48719]
        first_year_future: [50668]
        second_year_future: [53201]
      outer_london:
        current: [52068]
        first_year_future: [54151]
        second_year_future: [56858]
      inner_london:
        current: [58138]
        first_year_future: [60464]
        second_year_future: [63487]
    u3:
      rest_of_england:
        current: [49084]
        first_year_future: [51048]
        second_year_future: [53600]
      london_fringe:
        current: [50471]
        first_year_future: [52490]
        second_year_future: [55114]
      outer_london:
        current: [53994]
        first_year_future: [56154]
        second_year_future: [58961]
      inner_london:
        current: [60092]
        first_year_future: [62496]
        second_year_future: [65620]

    leading_practitioner:
      rest_of_england:
        current: [50025, 76050]
        first_year_future: [52026, 79092]
        second_year_future: [54627, 83046]
      london_fringe:
        current: [51403, 77430]
        first_year_future: [53460, 80528]
        second_year_future: [56133, 84554]
      outer_london:
        current: [53994, 80022]
        first_year_future: [56154, 83223]
        second_year_future: [58961, 87384]
      inner_london:
        current: [59478, 85509]
        first_year_future: [61858, 88930]
        second_year_future: [64950, 93376]
    leadership:
      rest_of_england:
        current: [49781, 138265]
        first_year_future: [51773, 143796]
        second_year_future: [54361, 150985]
      london_fringe:
        current: [51151, 139632]
        first_year_future: [53198, 145218]
        second_year_future: [55857, 152478]
      outer_london:
        current: [53731, 142178]
        first_year_future: [55881, 147866]
        second_year_future: [58675, 155259]
      inner_london:
        current: [59186, 147586]
        first_year_future: [61554, 153490]
        second_year_future: [64631, 161164]

test:
  paybands_and_spine_points: {}
  areas: {}
  pay_ranges: {}

production:
  <<: *default
