development: &default
  paybands_and_spine_points:
    unqualified:
      unq1: Unqualified Pay Range 1 (UnQ1)
      unq2: Unqualified Pay Range 2 (UnQ2)
      unq3: Unqualified Pay Range 3 (UnQ3)
      unq4: Unqualified Pay Range 4 (UnQ4)
      unq5: Unqualified Pay Range 5 (UnQ5)
      unq6: Unqualified Pay Range 6 (UnQ6)
    main:
      m1: Main Pay Range 1 (M1)
      m2: Main Pay Range 2 (M2)
      m3: Main Pay Range 3 (M3)
      m4: Main Pay Range 4 (M4)
      m5: Main Pay Range 5 (M5)
      m6: Main Pay Range 6 (M6)
    upper:
      u1: Upper Pay Range (U1)
      u2: Upper Pay Range (U2)
      u3: Upper Pay Range (U3)
    other:
      leading_practitioner: Leading Practitioner
      leadership: Leadership

  areas:
    inner_london: Inner London
    outer_london: Outer London
    london_fringe: Fringe of London
    rest_of_england: Rest of England

  pay_ranges:
    unq1:
      rest_of_england:
        current: [20598]
        future: [21731]
      london_fringe:
        current: [21933]
        future: [23140]
      outer_london:
        current: [24415]
        future: [25758]
      inner_london:
        current: [25831]
        future: [27252]
    unq2:
      rest_of_england:
        current: [22961]
        future: [24224]
      london_fringe:
        current: [24293]
        future: [25630]
      outer_london:
        current: [26779]
        future: [28252]
      inner_london:
        current: [28194]
        future: [29745]
    unq3:
      rest_of_england:
        current: [25323]
        future: [26716]
      london_fringe:
        current: [26656]
        future: [28123]
      outer_london:
        current: [29141]
        future: [30744]
      inner_london:
        current: [30557]
        future: [32238]
    unq4:
      rest_of_england:
        current: [27406]
        future: [28914]
      london_fringe:
        current: [28738]
        future: [30319]
      outer_london:
        current: [31229]
        future: [32947]
      inner_london:
        current: [32640]
        future: [34436]
    unq5:
      rest_of_england:
        current: [29772]
        future: [31410]
      london_fringe:
        current: [31102]
        future: [32813]
      outer_london:
        current: [33590]
        future: [35438]
      inner_london:
        current: [35000]
        future: [36925]
    unq6:
      rest_of_england:
        current: [32134]
        future: [33902]
      london_fringe:
        current: [33464]
        future: [35305]
      outer_london:
        current: [35954]
        future: [37932]
      inner_london:
        current: [37362]
        future: [39417]
    m1:
      rest_of_england:
        current: [30000]
        future: [31650]
      london_fringe:
        current: [31350]
        future: [33075]
      outer_london:
        current: [34514]
        future: [36413]
      inner_london:
        current: [36745]
        future: [38766]
    m2:
      rest_of_england:
        current: [31737]
        future: [33483]
      london_fringe:
        current: [33150]
        future: [34974]
      outer_london:
        current: [36320]
        future: [38318]
      inner_london:
        current: [38491]
        future: [40609]
    m3:
      rest_of_england:
        current: [33814]
        future: [35674]
      london_fringe:
        current: [35204]
        future: [37141]
      outer_london:
        current: [38219]
        future: [40322]
      inner_london:
        current: [40318]
        future: [42536]
    m4:
      rest_of_england:
        current: [36051]
        future: [38034]
      london_fringe:
        current: [37436]
        future: [39495]
      outer_london:
        current: [40218]
        future: [42430]
      inner_london:
        current: [42233]
        future: [44556]
    m5:
      rest_of_england:
        current: [38330]
        future: [40439]
      london_fringe:
        current: [39687]
        future: [41870]
      outer_london:
        current: [42654]
        future: [45000]
      inner_london:
        current: [44615]
        future: [47069]
    m6:
      rest_of_england:
        current: [41333]
        future: [43607]
      london_fringe:
        current: [42689]
        future: [45037]
      outer_london:
        current: [46001]
        future: [48532]
      inner_london:
        current: [47666]
        future: [50288]
    u1:
      rest_of_england:
        current: [43266]
        future: [45646]
      london_fringe:
        current: [44579]
        future: [47031]
      outer_london:
        current: [47592]
        future: [50210]
      inner_london:
        current: [52526]
        future: [55415]
    u2:
      rest_of_england:
        current: [44870]
        future: [47338]
      london_fringe:
        current: [46179]
        future: [48719]
      outer_london:
        current: [49353]
        future: [52068]
      inner_london:
        current: [55107]
        future: [58138]
    u3:
      rest_of_england:
        current: [46525]
        future: [49084]
      london_fringe:
        current: [47839]
        future: [50471]
      outer_london:
        current: [51179]
        future: [53994]
      inner_london:
        current: [56959]
        future: [60092]

    leading_practitioner:
      rest_of_england:
        current: [47417, 72085]
        future: [50025, 76050]
      london_fringe:
        current: [48723, 73393]
        future: [51403, 77430]
      outer_london:
        current: [51179, 75850]
        future: [53994, 80022]
      inner_london:
        current: [56377, 81051]
        future: [59478, 85509]
    leadership:
      rest_of_england:
        current: [47185, 131056]
        future: [49781, 138265]
      london_fringe:
        current: [48484, 132352]
        future: [51151, 139632]
      outer_london:
        current: [50929, 134765]
        future: [53731, 142178]
      inner_london:
        current: [56100, 139891]
        future: [59186, 147586]

test:
  paybands_and_spine_points: {}
  areas: {}
  pay_ranges: {}

production:
  <<: *default
