name: Build, test and deploy to AKS
concurrency: build_and_deploy_${{ github.ref_name }}

on:
  push:
    branches:
      - build-testing

jobs:
  build:
    name: Build and scan docker image
    runs-on: ubuntu-latest
    outputs:
      docker-image-tag: ${{ steps.build-image.outputs.tag }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build and push docker image
        id: build-image
        uses: DFE-Digital/github-actions/build-docker-image@build-docker-image-override-tags
        with:
          docker-repository: ghcr.io/dfe-digital/teacher-pay-calculator
          github-token: ${{ secrets.GITHUB_TOKEN }}
          snyk-token: ${{ secrets.SNYK_TOKEN }}
          context: .
          reuse-cache: true
          max-cache: true

  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run tests
        uses: ./.github/actions/run-tests
